### PR TITLE
GPG configuration fix

### PR DESCRIPTION
**Pull request by senivam**
Move GPG arguments to Execution section of the plugin

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Comment by bshannon** [comment]
Can you explain exactly what it is that this is fixing?

How does moving the configuration from global to the one execution help?

**Comment by kwsutter** [comment]
Unless this requested change is fixing something or possibly preventing an issue from surfacing, I'd recommend to leave this as-is.  More justification please.

**Comment by senivam** [comment]
The reason for the change is migration of the EE4J CI infrastructure. New JIPP which contains jobs for the parent pom.xml project fails to perform release of the actual parent pom.xml. The issue was escalated to Eclipse and described in the issue [548676](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548676). Proposed and discussed solution results in actual PR.

**Comment by pzygielo** [comment]
I'm not sure the cause is as described in 548676.

In build referenced there, https://ci-staging.eclipse.org/ee4j/job/ee4j-parent-master/48/console, just before BUILD FAILURE reported:
```
+ mvn -B -U -C clean verify gpg:sign
```
1. `sign` goal is called directly. It results with
```
[INFO] --- maven-gpg-plugin:1.6:sign (default-cli) @ project ---
```
(`default-cli`), and not execution defined in this pom `sign-artifacts`.

2. Profile `oss-release` is not activated.  So plugin is not configured at all. With this profile active proper goal is used with verify `goal`:
```
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ child ---
```
But if you `verify` with profile active, and call `gpg:sign` as separate goal you'll get two executions:
```
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ child ---
[INFO] 
[INFO] --- maven-gpg-plugin:1.6:sign (default-cli) @ child ---
```

**Comment by senivam** [comment]
perfect point! activation of oss-release profile solved the issue. Thanks! Closing the PR.

**Comment by pzygielo** [comment]
Consider dropping `gpg:sign` in https://ci-staging.eclipse.org/ee4j/job/ee4j-parent-master/52/console.
As said - `verify` phase includes it, but now you have two executions:
```
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ project ---
[INFO] 
[INFO] --- maven-gpg-plugin:1.6:sign (default-cli) @ project ---
```

**Comment by senivam** [comment]
yes, gpg:sign removed as well. Thanks for the help :)

**Pull request closed without merging**
