### PR TITLE
Add license text file

### LINKED ISSUE #40: Include license text as separate file
Having a separate license file is more convenient for packaging purposes.

### PR DESCRIPTION
**Pull request by ivargrimstad**
This PR closes #40

### CODE REVIEW

**Comment by bshannon** [comment]
Since this came up in the context of JAF and JavaMail, note that this license
file is not correct for either JAF or JavaMail.

JavaMail uses EPLv2 with a secondary license of GPLv2+CE.
JAF uses EDL.

**Comment by waynebeaton** [comment]
The standard license for EE4J projects is EPL-2.0 with GPL-2.0+Classpath exception. The License file should indicate all licenses be like what is in the the JavaMail project's root.

https://github.com/eclipse-ee4j/javamail/blob/master/LICENSE.md

Most of the projects use this licensing scheme. The Foundation Database records the following exceptions:

- ee4j.eclipselink (EDL1.0 OR EPL-2.0)
- ee4j.jaf (EDL1.0 OR EPL-2.0 OR GPL-2.0_CP)
- ee4j.jaxb (EDL1.0)
- ee4j.jaxb-impl (EDL1.0)
- ee4j.jaxws (EDL1.0)
- ee4j.jpa (EDL1.0 OR EPL-2.0)
- ee4j.krazo (ASL2.0)
- ee4j.metro (EDL1.0)
- ee4j.orb (EDL1.0 OR EPL-2.0 OR GPL-2.0_CP)
- ee4j.yasson (EDL1.0 OR EPL1.0)

It would be good to know if something is either missing from this list or is otherwise incorrect.

**Comment by waynebeaton** [comment]
FWIW, the proper SPDX license expression is (EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0).

Note that SPDX expressions are crafted from the perspective of the consumer. From a consumer's point of view, the content can be consumed under either of the specified licenses. "AND" would suggest that both licenses must be accepted.

**Comment by waynebeaton** [comment]
FYI, @bshannon noticed that the licenses listed in our database for Eclipse ORB and Eclipse Project for JAF do not match the license files in the respective project repositories. I've opened [Bug 544845](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544845) to track the approval of the change.

**Comment by waynebeaton** [comment]
> FYI, @bshannon noticed that the licenses listed in our database for Eclipse ORB and Eclipse Project for JAF do not match the license files in the respective project repositories. I've opened [Bug 544845](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544845) to track the approval of the change.

This is not a blocker. Please just make sure that the correct license (as stated in the repository) is expressed in the exception.

**Pull request merged**
