### PR TITLE
Inception year and default developer block updated

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by karianna** [comment]
Closes #19 and updates #12

**Comment by lukasj** [comment]
I agree with this change (I feel I should say something when my name is involved...)

**Comment by karianna** [comment]
@lukasj Thanks and apologies for not mentioning you directly so you could take a look!

**Comment by karianna** [comment]
It's already there?

Cheers,
Martijn

**Comment by karianna** [comment]
@mkarg Given that IntelliJ dominates the IDE space for developers and that the target dir is created by executing Maven, this is probably OK?

**Comment by ivargrimstad** [comment]
I agree with @mkarg regarding .gitignore. I must admit, though, that I usually put IDE artifacts in the repository .gitignore to avoid lazy devs committing these artifacts by accident, so I am fine with keeping them.

**Comment by mkarg** [comment]
@karianna Thanks for removing it. Independend of any current market shares we should be fair and not support any particular product.

**Comment by m0mus** [comment]
@karianna I didn't understand what you mean. Email address is not in the developer section. I suggested to add it, like this:

    <email>jakarta.ee-community@eclipse.org</email>

or

    <email>ee4j-pmc@eclipse.org</email>

**Comment by karianna** [comment]
@m0mus Gotcha - OK added.

**Comment by karianna** [comment]
Can this be merged now?

**Pull request merged**
